server:
  port: 9999
  servlet:
    context-path: /
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3310/ezs?useSSL=false&useUnicode=true&characterEncoding=utf-8
#    url: jdbc:p6spy:mysql://127.0.0.1:3310/ezs?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true


#decorator:
#  datasource:
#    p6spy:
#      # 全部可用参数参照该类：com.p6spy.engine.spy.appender.CustomLineFormat
#      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
#      # 自定义日志类的作用仅仅是改变了打印的颜色，如果不需要可以不加
#      logging: custom
#      custom-appender-class: com.example.testinit.config.StdoutLogger


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: 'com.gpt806.ezs.controller'

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  documents:
    - group: 2.X版本
      name: 接口签名
      locations: classpath:/*
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.gpt806.ezs.entity
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl